### ISSUE TITLE
Which Hardware do you use exactyl

### ISSUE THREAD

**Issue by hannespreishuber** [Microsoft/Windows-appsample-huelightcontroller#3]
do i need a bridge?

**Comment by awkoren** [comment]
@hannespreishuber Yes, you'll need a bridge and at least 1 light. Our app was built and tested using a Philips Hue 1st generation bridge. I assume the app would still work with a 2nd/3rd gen bridges, although you might need to make tweaks to the REST API calls.

**Comment by awkoren** [comment]
Closing issue for now, feel free to reopen if you have more questions.
